### ISSUE TITLE
Change channels

### ISSUE THREAD

**Issue by AntiSlang** [HoroTW/pixoo-awesome#3]
Hello, sorry for writing here instead of pixoo_client (they don't answer), but please answer if you can. I want to automate screen change and already found out that _pixoo.set_box_mode(4, 4)_ makes "matrix" voice screen, and now I need to change clock screen. So in _set_box_mode(self, boxmode, visual=0, mode=0)_ boxmode should be 1, but how can I do turning on the clock I need and its channels (weather, temperature and calendar)?

**Comment by HoroTW** [comment]
pixoo-awesome is only using the pixoo client for the "drawing" the pixels manually.
The default channels of the device can be activated with the pixoo client but I don't remember how.
I'm sorry but I don't think I can help you.

**Comment by AntiSlang** [comment]
> pixoo-awesome is only using the pixoo client for the "drawing" the pixels manually. The default channels of the device can be activated with the pixoo client but I don't remember how. I'm sorry but I don't think I can help you.

thanks
